# Return formats
JSON = 'JSON'
CSV = 'CSV'
TABLE = 'TABLE'

# Size units
BYTES = 'B'
KILOBYTES = 'KB'
MEGABYTES = 'MB'
GIGABYTES = 'GB'
TERABYTES = 'TB'

# Storage types
STANDARD = 'STANDARD'
INFREQUENT_ACCESS = 'STANDARD_IA'
REDUCED_REDUNDANCY = 'REDUCED_REDUNDANCY'

# Stat groups
TOTAL = 'TOTAL'
BY_BUCKET = 'BY_BUCKET'
BY_STORAGE_TYPE = 'BY_STORAGE_TYPE'
BY_REGION = 'BY_REGION'
